services:
  go_db:
    image: postgres:latest
    container_name: go_db
    environment:
      POSTGRES_DB: neoway
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    networks:
      - cluster

  go_app:
    build:
      context: .
    container_name: go_app
    environment:
      DB_HOST: go_db
      DB_PORT: 5432
      DB_DATABASE: neoway
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_SCHEMA: public
    depends_on:
      - go_db
    ports:
      - 8080:8080
    networks:
      - cluster

volumes:
  psql_volume:

networks:
  cluster:
    driver: bridge